name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          node_modules
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install npm dependencies
      run: npm ci
      shell: bash

