name: Test my project
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: PHP version
        run: php -v
      - name: Composer version
        run: composer --version
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
            path: /tmp/composer-cache
            key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist
      - name: Run Unit tests
        run: php ./vendor/bin/phpunit --testsuite Unit
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: PHP version
        run: php -v
      - name: Composer version
        run: composer --version
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist
      - name: Create database schema
        run: |
            php bin/console doctrine:database:create --if-not-exists --env=test
            php bin/console doctrine:schema:create --env=test
      - name: Run integration tests
        run: php ./vendor/bin/phpunit --testsuite Integration
  build:
    needs: [unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install npm dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: 'public/build'

