name: Test my project
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: PHP version
        run: php -v
      - name: Composer version
        run: composer --version
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
            path: /tmp/composer-cache
            key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist
      - name: Run Unit tests
        run: php vendor/bin/phpunit --testsuite Unit
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install NPM dependencies
        run: npm install
      - name: Build assets
        run: npm run build
