name: Test my project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: PHP version
        run: php -v
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install composer
        uses: php-actions/composer@v6
      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist
      - name: Run Unit tests
        run: php vendor/bin/phpunit --testsuite Unit

